# Generated by Django 2.1.4 on 2019-01-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='title',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
